### ISSUE TITLE
Feature: 카테고리 기능 구현

### ISSUE THREAD

**Issue by HwangSeungHyeon** [HwangSeungHyeon/buysell#3]
## Description
카테고리 CRUD 기능 구현

## Todo
- [x] 카테고리 등록, 수정, 삭제
- [x] 카테고리 목록 조회
- [x] 카테고리별 게시글 조회

## ETC
카테고리 등록, 수정, 삭제는 ENUM 클래스를 이용하여 관리합니다.
