### ISSUE TITLE
Feature: redis를 이용한 캐시 기능 구현

### ISSUE THREAD

**Issue by HwangSeungHyeon** [HwangSeungHyeon/buysell#43]
## Description
redis를 이용하여 사용자가 많이 이용할만한 서비스에 캐시를 적용한다.

## Todo
- [x] redis 설정
- [x] redis 연동
- [ ] 검색 결과를 redis 캐시에 저장
- [ ] 내가 본 게시글을 redis 캐시에 저장
- [ ] Amazon Elastic Cache를 사용하도록 변경

## ETC
우선 local redis에서 작업 후, 나중에 Elastic Cache 등으로 변경
