### ISSUE TITLE
Feature: CI 테스트

### ISSUE THREAD

**Issue by HwangSeungHyeon** [HwangSeungHyeon/buysell#54]
## Description
지속적 통합(CI)를 적용해본다

## Todo
- [x] CI : gradle Build 테스트를 제외하고 수행해보기
- [x] CI : gradle test 수행해보기
- [x] CI: build가 실패했을 때 슬랙으로 알림이 오도록 바꾸기

## ETC
CI 공부를 병행하면서 테스트해보기
