### ISSUE TITLE
Feature: Redis를 적용한 선착순 쿠폰발급 기능

### ISSUE THREAD

**Issue by lazzzykim** [HwangSeungHyeon/buysell#60]
## Description
redis를 적용한 선착순 쿠폰발급 시스템 구현

## Todo
- [x] Coupon domain 작성
- [x] Redis increment 적용
- [x] Set collection 적용해 1인당 1개의 쿠폰 발급받는 기능구현

## ETC
그 외 기타사항은 이곳에 작성해주세요
