### ISSUE TITLE
Feature: 결제 기능 구현

### ISSUE THREAD

**Issue by HwangSeungHyeon** [HwangSeungHyeon/buysell#8]
## Description
결제 기능을 구현합니다.
결제는 우선 사용자가 입력한 값을 DB에 저장한 후, 그 값으로 결제를 진행하는 방식을 채택합니다.

## Todo
- [x] 사용자가 입력한 값을 DB에 저장
- [x] 사용자가 입력한 값을 DB에서 가져와서 결제 진행
- [x] 결제 후 잔액 정상인지 확인
- [x] 결제 불가능 할 경우 throw exception

## ETC
추후, 실제 결제 기능으로 발전시킵니다.
